/**
 * Copyright (c) 2012, Stephan Aiche.
 *
 * This file is part of GenericKnimeNodes.
 * 
 * GenericKnimeNodes is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.07 at 11:16:19 AM CEST 
//

package com.genericworkflownodes.knime.cliwrapper;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for cliElementType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="cliElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mapping" type="{}mappingType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="optionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isList" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class CLIElement {

    /**
     * The mappings for this element.
     */
    private List<CLIMapping> mapping;

    /**
     * The identifier of this option. Can be an empty string if the
     * {@link CLIElement} is an argument.
     */
    private String optionIdentifier;

    /**
     * Indicates if the CLIElement is mapped to a list.
     */
    private Boolean isList;

    /**
     * Indicates whether the {@link CLIElement} is required for the cmd or not.
     */
    private Boolean required;

    /**
     * Gets the value of the mapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getMapping().add(newItem);
     * </pre>
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CLIMapping }
     * 
     * @return The list of available mappings for the current element.
     * 
     */
    public final List<CLIMapping> getMapping() {
        if (mapping == null) {
            mapping = new ArrayList<CLIMapping>();
        }
        return this.mapping;
    }

    /**
     * Gets the value of the optionIdentifier property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public final String getOptionIdentifier() {
        return optionIdentifier;
    }

    /**
     * Sets the value of the optionIdentifier property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public final void setOptionIdentifier(final String value) {
        this.optionIdentifier = value;
    }

    /**
     * Gets the value of the isList property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public final Boolean isList() {
        return isList;
    }

    /**
     * Sets the value of the isList property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public final void setIsList(final Boolean value) {
        this.isList = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public final Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public final void setRequired(final Boolean value) {
        this.required = value;
    }

}
